### ISSUE TITLE
Really a sugestion 4 you:

### ISSUE THREAD

**Issue by IanKavaYT** [xman213/minecraftatschool#1]

**Comment by IanKavaYT** [comment]
Shit i pressed enter by accident. Anyways, would it be hard to make a tlauncher that works at school? Or some pvp clients like Lunar and Badlion. Love these projects, 
IanKava

**Comment by xman213** [comment]
I got tluncher working on my school
Laptop on Minecraft version 1.12.2 I will put a download later this week

**Comment by xman213** [comment]
If you want to add me on discord I could give you 1.12.2 cracked Minecraft
for the school laptops  before I release it to the public

My discord is xman#1111

**Comment by IanKava** [comment]
I fucking love you
Il add you later 2day
Do I have any classes with you?
https://user-images.githubusercontent.com/77802993/130447080-5f48531b-0e43-44cf-a1f7-e892d47f6a91.png
Check the png photo link

**Comment by IanKava** [comment]
Do you have gmail? We could communicate on hangouts during school time. Mine is ianveraskavaleuski@gmail.com
Msg me

**Comment by IanKava** [comment]
I found a version of Lunar client that should be easyer to crack than the OG one: Lunar Lite. 
https://github.com/Aetopia/Lunar-Client-Lite-Launcher
You should really check it out!

**Comment by Aetopia** [comment]
> I found a version of Lunar client that should be easyer to crack than the OG one: Lunar Lite. 
> https://github.com/Aetopia/Lunar-Client-Lite-Launcher
> You should really check it out!

not going to work, you need to sign with either a microsoft or mojang account to use lunar client. lc lite just wraps and launches lunar.

**Comment by Aetopia** [comment]
> There is a few problems with bypassing Lunar client. 1. They download the game files from Mojang's servers and Mojang's servers are blocked by the firewall. 

you could just copy the game directory and lunar client files and then use lc lite to launch lunar.

**Comment by xman213** [comment]
That was the first thing that I Tried. and it did not work. somthing is blocking the LCL.exe file. I am looking to find out what is blocking it and how to bypass it

**Comment by Aetopia** [comment]
> 
> 
> That was the first thing that I Tried. and it did not work. somthing is blocking the LCL.exe file. I am looking to find out what is blocking it and how to bypass it

Its likely windows defender.
Code signing it also is useless cuz it also gets flagged even with code signing.

**Comment by xman213** [comment]
I think my school is using a registry key or some sort of auto game detection through McAfee endpoint security.

**Comment by IanKavaYT** [comment]
cool
